# Set the general logging level within the application
logging:
  level:
    io.pivotal.refarch: DEBUG
    org.hibernate.SQL: INFO
    com.zaxxer.hikari: DEBUG

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximumPoolSize: 3
      leakDetectionThreshold: 30000
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # database-platform: org.hibernate.dialect.MySQLMyISAMDialect
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true

your:
  host:
    is: "Allard Buijze"
