# Set the general logging level within the application
logging:
  level:
    io.pivotal.refarch: DEBUG
    org.hibernate.SQL: INFO
    com.zaxxer.hikari: DEBUG

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximumPoolSize: 3
      leakDetectionThreshold: 5000
      connectionTimeout: 30000
      idleTimeout: 30000 # The minimum allowed value is 10000ms (10 seconds). Default: 600000 (10 minutes) 
      maxLifetime: 60000 # A value of 0 indicates no maximum lifetime (infinite lifetime), subject of course to the idleTimeout setting. Default: 1800000 (30 minutes)
      
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # database-platform: org.hibernate.dialect.MySQLMyISAMDialect
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true

your:
  host:
    is: "Allard Buijze"
